// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMRNbbKX_oqEcM3Sgc8Cv2VNXw7prVMmE',
    appId: '1:324487940700:android:d659fd5df7572c91a57499',
    messagingSenderId: '324487940700',
    projectId: 'movietracker-fec75',
    databaseURL: 'https://movietracker-fec75-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movietracker-fec75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOUT-dAuXPKAIUS4-g512nHbo4ztyScS4',
    appId: '1:324487940700:ios:c4c8887fb28e05fda57499',
    messagingSenderId: '324487940700',
    projectId: 'movietracker-fec75',
    databaseURL: 'https://movietracker-fec75-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movietracker-fec75.firebasestorage.app',
    iosBundleId: 'com.example.movieTracers',
  );

}